### ISSUE TITLE
car-mirror: Change SR to SGR to avoid confusion with Skip Ratchet

### ISSUE THREAD

**Issue by justindotpub** [fission-suite/spec#16]
Up to you @expede, but submitting this to track that you mentioned it should probably change.  If this is changed across the board, it's one more char in the payload, but maybe who cares?  3 chars seems pretty fine in other protocol payloads.

**Comment by expede** [comment]
It's one character: go wild!

**Comment by expede** [comment]
What's the `G`?

**Comment by expede** [comment]
Sub Graph Roots!

**Comment by expede** [comment]
We could also use `ep` as entry points 🤔 Naming, I tell ya!

**Comment by expede** [comment]
Fixed in https://github.com/wnfs-wg/car-mirror-http/pull/1
