### ISSUE TITLE
Specify Bloom Filter Indexing

### ISSUE THREAD

**Issue by expede** [fission-suite/spec#2]
* [ ] Modulus
* [ ] RECOMMEND `m` to be a power of two
* [ ] MUST resample otherwise — define resampling method

**Comment by justindotpub** [comment]
I ended up using @matheus23's approach used in https://github.com/matheus23/rust-set-reconciliation/blob/4cbe2079600df906b9e18bff1f6a177ac7242cc3/src/ibf.rs#L128-L168, but with the uniqueness check removed.

Hasher iterator pattern
https://github.com/fission-suite/car-mirror/blob/f325c5ab651abb5452ced313243c91bb1ac57775/bloom/bloom.go#L105-L162

Use of Hasher for adding to and testing bloom filter
https://github.com/fission-suite/car-mirror/blob/f325c5ab651abb5452ced313243c91bb1ac57775/bloom/bloom.go#L65-L89

We also need to specify endianness for the bit set.  The current implementation uses big endian.
