### ISSUE TITLE
car-mirror: Provider/Requestor + Sender/Receiver + Push/Pull terminology is confusing

### ISSUE THREAD

**Issue by softwareplumber** [fission-suite/spec#24]
So far as I can see, the protocol can be simply defined in terms of messages exchanged between a block source and a block sink.

Provider/Requestor is largely a matter of perspective - who is initiating the exchange. In most rounds, there should not be a great difference between 'push' and 'pull' excepting that the 'request' and 'response' message types are switched. The actual sequence of messages remains essentially the same - except, obviously, for the initial setup and termination conditions.

When reading the spec I find myself frequently having to re-read sentences having initially assumed that 'Provider' means 'Block Provider' (e.g. Sender) or 'Requestor' means 'Block Requestor' (e.g. Receiver) when this is only the case for a pull operation.

I believe the spec will be clearer and easier to read by adjusting the majority of the wording to refer to 'Car' and 'Status' message types exchanged between a Block Source and Block Sink, then later explaining how a Block Sink can initiate a 'Pull' session by sending a 'Status' message to a Block Source and that a Block Source can initiate a 'Push' session by sending a 'Car' message to a Block Sink.

**Comment by expede** [comment]
Fair! There is a difference between push and pull in nodes that are not dialable. I agree that the middle portion of the algorithm could introduce the source/sink terminology and be abstracted out 💯

**Comment by expede** [comment]
Fixed in https://github.com/wnfs-wg/car-mirror/pull/1
